// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMNI.Data.Data;

namespace OMNI.Data.Data.Migrations.OMNIDbMigrations
{
    [DbContext(typeof(OMNIDbContext))]
    [Migration("20220718005253_Create new OMNIDb")]
    partial class CreatenewOMNIDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OMNI.Data.Data.Dao.LLPTrx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<float>("DetailExisting")
                        .HasColumnType("real");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("KesesuaianOSCP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KesesuaianPM58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kondisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PersentaseHubla")
                        .HasColumnType("real");

                    b.Property<float>("PersentaseOSCP")
                        .HasColumnType("real");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<float>("RekomendasiOSCP")
                        .HasColumnType("real");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SelisihHubla")
                        .HasColumnType("real");

                    b.Property<float>("SelisihOSCP")
                        .HasColumnType("real");

                    b.Property<int?>("SpesifikasiJenisId")
                        .HasColumnType("int");

                    b.Property<float>("TOtalKebutuhanHubla")
                        .HasColumnType("real");

                    b.Property<float>("TotalExistingJenis")
                        .HasColumnType("real");

                    b.Property<float>("TotalKebutuhanOSCP")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("SpesifikasiJenisId");

                    b.ToTable("LLPTrx");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.Latihan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Latihan");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.LatihanTrx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("KesesuaianPM58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatihanId")
                        .HasColumnType("int");

                    b.Property<float>("PersentaseLatihan")
                        .HasColumnType("real");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SelisihHubla")
                        .HasColumnType("real");

                    b.Property<DateTime>("TanggalPelaksanaan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("LatihanId");

                    b.ToTable("LatihanTrx");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.PeralatanOSR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("PeralatanOSR");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.Personil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Personil");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.PersonilTrx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("KesesuaianPM58")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PersentasePersonil")
                        .HasColumnType("real");

                    b.Property<int?>("PersonilId")
                        .HasColumnType("int");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SelisihHubla")
                        .HasColumnType("real");

                    b.Property<int>("SisaMasaBerlaki")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalExpired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalPelatihan")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalDetailExisting")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("PersonilId");

                    b.ToTable("PersonilTrx");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.SpesifikasiJenis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeralatanOSRId")
                        .HasColumnType("int");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RekomendasiHubla")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("PeralatanOSRId");

                    b.ToTable("SpesifikasiJenis");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.LLPTrx", b =>
                {
                    b.HasOne("OMNI.Data.Data.Dao.SpesifikasiJenis", "SpesifikasiJenis")
                        .WithMany()
                        .HasForeignKey("SpesifikasiJenisId");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.LatihanTrx", b =>
                {
                    b.HasOne("OMNI.Data.Data.Dao.Latihan", "Latihan")
                        .WithMany()
                        .HasForeignKey("LatihanId");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.PersonilTrx", b =>
                {
                    b.HasOne("OMNI.Data.Data.Dao.Personil", "Personil")
                        .WithMany()
                        .HasForeignKey("PersonilId");
                });

            modelBuilder.Entity("OMNI.Data.Data.Dao.SpesifikasiJenis", b =>
                {
                    b.HasOne("OMNI.Data.Data.Dao.PeralatanOSR", "PeralatanOSR")
                        .WithMany()
                        .HasForeignKey("PeralatanOSRId");
                });
#pragma warning restore 612, 618
        }
    }
}
